   -- $$$$$$$$$$$$$$$$   HEALTHCARE_PROJECT    $$$$$$$$$$$$$$$$ --      
   -- SELECT DATABASE --
   USE HEALTHCARE_PROJECT;

   -- SHOW RECORDS IN THE TABLE --
   SELECT * FROM HEALTHCARE;

/* Write SQL queries to retrieve and 
manipulate data for below questions :
1. Retrieve the names of all patients in the 
database. 
2. List the unique medical conditions present in 
the dataset. 
3. Find the total number of doctors in the 
healthcare system. 
4. Retrieve the details of all female patients. 
5. what is the average age of patients in the 
database.
6. Identify the patients who have more than one 
medical condition. 
7. List the names of all doctors. 
8.Identify the most common medical condition 
among patients.
9.Find the patients who are older than 60 years 
and have diabetes. 
10.Calculate the total revenue generated by the 
healthcare system. 
11.Find the doctor with the oldest patient.
12.Calculate the average duration of medical 
visits.
13.Give the names of patients whose name starts 
with A. 
14.How many male and female patients are there 
in dataset. 
15.how many patients are normal. 
16.how many patients are abnormal or 
Inconclusive.
17.how many patients of blood group AB+ are 
there of age above 52. 
18. how many patients have paid the bill above 
24890. 
19. what are the names of patients having 
Asthma. 
20. how many patients have cancer. 
21. what are the names and blood groups of 
patients admitted to room no. 292. 
22. how many males have Arthritis.
23. How many patients were admitted to Harris 
and Sons hospital. 
24. what are the names of patients whose 
Insurance Provider are Cigna. 
25. Name the Medical Condition having patients 
whose ages is greater than average age */

   -- SOLUTIONS --
      -- 1. Retrieve the names of all patients in the database --
    SELECT NAME FROM HEALTHCARE;
 
    -- 2. List the unique medical conditions present in the dataset --
    SELECT DISTINCT MEDICAL_CONDITION FROM HEALTHCARE;
 
    -- 3. Find the total number of doctors in the healthcare system. --
    SELECT COUNT(DOCTOR) FROM HEALTHCARE;
	--          OR                     -- 
    SELECT DISTINCT COUNT(DOCTOR) FROM HEALTHCARE;
  
    -- 4. Retrieve the details of all female patients --
    SELECT * FROM HEALTHCARE WHERE GENDER ='FEMALE'; 
   
   -- 5. what is the average age of patients in the database. --
    SELECT AVG(AGE) FROM HEALTHCARE;
   
   
    -- 6. Identify the patients who have more than one  medical condition. --
    SELECT * FROM HEALTHCARE;
   
    SELECT NAME,COUNT(MEDICAL_CONDITION) AS MEDICAL_CONDITION_COUNT FROM HEALTHCARE GROUP BY NAME HAVING COUNT(MEDICAL_CONDITION) > 1;
   
    --          OR                     -- 
      SELECT NAME,
		     COUNT(MEDICAL_CONDITION) AS MEDICAL_CONDITION_COUNT 
      FROM 
             HEALTHCARE 
      GROUP BY 
            NAME 
	  HAVING 
      COUNT(MEDICAL_CONDITION) > 1;
	
    -- 7. List the names of all doctors. --
    SELECT DOCTOR FROM HEALTHCARE;
   
    -- 8.Identify the most common medical condition among patients. --
    SELECT MEDICAL_CONDITION FROM HEALTHCARE GROUP BY MEDICAL_CONDITION ORDER BY COUNT(MEDICAL_CONDITION) DESC LIMIT 1;
   
    -- 9.Find the patients who are older than 60 years and have diabetes. --
    SELECT NAME FROM HEALTHCARE WHERE AGE > 60 AND MEDICAL_CONDITION ='DIABETES';
  
    -- 10.Calculate the total revenue generated by the healthcare system. --
    SELECT SUM(BILLING_AMOUNT) FROM HEALTHCARE;
  
    -- 11.Find the doctor with the oldest patient. --
    SELECT DOCTOR,NAME FROM HEALTHCARE ORDER BY AGE DESC LIMIT 1;
  
    --  12.Calculate the average duration of medical visits --
    SELECT AVG(DURATION) FROM HEALTHCARE;
   
    -- 13.Give the names of patients whose name starts with A. --
    SELECT NAME FROM HEALTHCARE WHERE NAME LIKE 'A%';
   
    -- 14.How many male and female patients are there in dataset. --
    SELECT GENDER,COUNT(GENDER) FROM HEALTHCARE GROUP BY GENDER;

    -- 15.how many patients are normal. --
    SELECT TEST_RESULTS,COUNT(TEST_RESULTS) FROM HEALTHCARE WHERE TEST_RESULTS ='NORMAL';
   
    -- # 16.how many patients are abnormal or Inconclusive. --
    SELECT TEST_RESULTS,COUNT(*) FROM HEALTHCARE WHERE TEST_RESULTS IN('INCONCLUSIVE','ABNORMAL') GROUP BY TEST_RESULTS;
   
    --          OR                     -- 
      SELECT TEST_RESULTS, COUNT(*) AS XYZ
      FROM HEALTHCARE
      WHERE TEST_RESULTS IN ('ABNORMAL', 'INCONCLUSIVE')
      GROUP BY TEST_RESULTS;
   
    -- 17.how many patients of blood group AB+ are there of age above 52. -- 
    SELECT COUNT(BLOOD_TYPE) FROM HEALTHCARE WHERE BLOOD_TYPE ='AB+' AND AGE >52;

    -- 18. how many patients have paid the bill above 24890. --
    SELECT COUNT(BILLING_AMOUNT) FROM HEALTHCARE WHERE BILLING_AMOUNT >24890;

    --          OR                     -- 
    SELECT COUNT(*) FROM HEALTHCARE WHERE BILLING_AMOUNT >24890;

    -- 19. what are the names of patients having Asthma. --
    SELECT NAME FROM HEALTHCARE WHERE MEDICAL_CONDITION ='ASTHMA';


    -- 20. how many patients have cancer. --
    SELECT COUNT(*) FROM HEALTHCARE WHERE MEDICAL_CONDITION ='CANCER';

    --          OR                     -- 
    SELECT COUNT(MEDICAL_CONDITION) FROM HEALTHCARE WHERE MEDICAL_CONDITION ='CANCER';

    -- 21. what are the names and blood groups of patients admitted to room no. 292. --
    SELECT NAME,BLOOD_TYPE FROM HEALTHCARE WHERE ROOM_NUMBER = 292;

    -- 22. how many males have Arthritis.--
    SELECT COUNT(GENDER) FROM HEALTHCARE WHERE GENDER ='MALE' AND MEDICAL_CONDITION = 'ARTHRITIS';

    -- 23. How many patients were admitted to Harris and Sons hospital. --
    SELECT COUNT(*) FROM HEALTHCARE WHERE HOSPITAL ='HARRIS AND SONS';

    -- 24. what are the names of patients whose Insurance Provider are Cigna. --
    SELECT NAME,INSURANCE_PROVIDER FROM HEALTHCARE WHERE INSURANCE_PROVIDER ='CIGNA';

    -- 25. Name the Medical Condition having patients whose ages is greater than average age --
    SELECT AVG(AGE) FROM HEALTHCARE;
    SELECT AGE,NAME,MEDICAL_CONDITION FROM HEALTHCARE WHERE AGE > (SELECT AVG(AGE) FROM HEALTHCARE);


   
   




  
  
 